server:
    port: 8080
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: kslang
            username: kslang
            password: kslang9819!@
    thymeleaf:
        cache: false